### PR TITLE
Fix #305: Fix UnhandledRejectionWarning with EEXIST

### LINKED ISSUE #305: UnhandledRejectionWarning with EEXIST error appears when running bundler
When the bundler is run and a corrupted manifest/build directory is found, the bundler fails with an `UnhandledRejectionWarning` when trying to rename a package directory.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

File: packages/liferay-npm-bundler/src/util.js [hunk 1]
```diff
@@ -109,6 +101,8 @@ export function renamePkgDirIfPkgJsonChanged(pkg) {
 			getPackageTargetDir(pkgJson.name, pkgJson.version)
 		);
 
+		rimraf.sync(`${newDir}/**`);
+
```
Comment (wincent) [inline packages/liferay-npm-bundler/src/util.js]: Changes to `iterateSerially()` look good but how is this related?

Comment (wincent) [reply packages/liferay-npm-bundler/src/util.js]: And also, why not `rimraf.sync(newDir)`?

Comment (izaera) [reply packages/liferay-npm-bundler/src/util.js]: 1. It is not necessary to fix the bug, but it helped me to diagnose the problem and decided to include it as the code looks much better.

2. :thinking: That's true: `${newDir}/**` should fail because it looks like it won't delete the folder itself but for some reason, it works :man_shrugging: . I'll check again.

Comment (izaera) [reply packages/liferay-npm-bundler/src/util.js]: Both seems to work so I'll change it to remove the `**`
